---
- name: Configure Web Server with Nginx
  hosts: webservers # Refers to the 'webservers' group in the inventory file
  become: yes         # Execute tasks with sudo privileges

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600 # Cache for 1 hour

    - name: Install Nginx
      ansible.builtin.apt:
        name: nginx
        state: present

    - name: Ensure Nginx service is running and enabled
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes

    - name: Deploy custom index.html (optional)
      ansible.builtin.copy:
        content: "<h1>Hello from Ansible on AWS!</h1>"
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'